name: Build Samsung A51 Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            bc \
            git \
            wget \
            curl

      - name: Set up Proton Clang-10
        run: |
          mkdir -p toolchain
          cd toolchain
          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20201010.tar.gz -O proton-clang-10.tar.gz
          tar -xzf proton-clang-10.tar.gz
          rm proton-clang-10.tar.gz
          export PATH="$(pwd)/proton-clang-20201010/bin:$PATH"
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          export PLATFORM_VERSION=13

      - name: Build kernel
        run: |
          make exynos9610_a51xx_defconfig
          make -j$(nproc) CC=clang LD=ld.lld

      - name: Check build artifacts
        id: check_files
        run: |
          if [ -f arch/arm64/boot/Image ] && [ -f arch/arm64/boot/dtb.img ]; then
            echo "artifacts_exist=true" >> $GITHUB_OUTPUT
          else
            echo "artifacts_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload build artifacts
        if: steps.check_files.outputs.artifacts_exist == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dtb.img
            arch/arm64/boot/dts/exynos/*.dtbo
